# Generated by Django 4.1.1 on 2022-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_item_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_off', models.IntegerField(default=20)),
                ('duration', models.CharField(default='once', max_length=255)),
                ('order', models.ManyToManyField(related_name='discounts', to='api.order')),
            ],
        ),
    ]
