# Generated by Django 4.1.1 on 2022-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_order_discount_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Sales Tax', max_length=255)),
                ('inclusive', models.BooleanField(default=False)),
                ('percentage', models.DecimalField(decimal_places=2, default=7.25, max_digits=4)),
                ('country', models.CharField(default='US', max_length=255)),
                ('state', models.CharField(default='CA', max_length=255)),
                ('jurisdiction', models.CharField(default='US - CA', max_length=255)),
                ('description', models.CharField(default='CA Sales Tax', max_length=255)),
                ('orders', models.ManyToManyField(related_name='tax_rates', to='api.order')),
            ],
        ),
    ]
