# Generated by Django 4.1.1 on 2022-09-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_taxrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='orders',
        ),
    ]
